name: discover_majalengka
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  get: 4.6.5
  intl: ^0.17.0
  validators: ^3.0.0
  encrypted_shared_preferences: ^2.0.0
  device_info_plus: ^8.0.0
  envied: ^0.3.0

dev_dependencies: 
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
      - assets/images/

